version: "2"
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-73
  eslint:
    enabled: false
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  brakeman:
    enabled: true

exclude_patterns:
  - "spec/"
  - "**/specs/"
  - "db/*"
  - "bin/**/*"
  - "db/**/*"
  - "config/**/*"
  - "public/**/*"
  - "vendor/**/*"
  - "node_modules/**/*"
  - "lib/tasks/auto_annotate_models.rake"
  - "app/test-matchers.js"
